# Generated by Django 3.2.3 on 2022-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LauncherId', models.CharField(default='noId', max_length=10)),
                ('username', models.CharField(default='notSignedIn', max_length=100)),
                ('version', models.CharField(default='notUpdated', max_length=10)),
                ('lastUsedDate', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=12)),
                ('head', models.CharField(default='Headline not specified', max_length=200)),
                ('text', models.TextField(default='Body text not specified', max_length=10000)),
                ('date', models.CharField(default='No Date', max_length=10)),
                ('url', models.CharField(default='none', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='0', max_length=1)),
                ('minor', models.CharField(default='0', max_length=1)),
                ('patch', models.CharField(default='0', max_length=1)),
            ],
        ),
    ]
