# Generated by Django 3.2.3 on 2022-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadeLauncher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(default=0, max_length=12)),
                ('two', models.CharField(default=0, max_length=12)),
                ('three', models.CharField(default=0, max_length=12)),
            ],
        ),
    ]
