# Generated by Django 3.2.3 on 2022-06-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadeLauncher', '0002_newscodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscodes',
            options={'verbose_name_plural': 'News Codes'},
        ),
    ]
