# Generated by Django 4.1.2 on 2022-10-26 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadeLauncher', '0004_auto_20220724_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
