# Generated by Django 4.1.2 on 2022-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadeLauncher', '0006_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
