# Generated by Django 4.1.2 on 2022-11-01 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jadeLauncher', '0008_remove_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
