# Generated by Django 3.2.3 on 2022-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('plus', models.CharField(default='False', max_length=5)),
                ('dateCreated', models.DateField(blank=True)),
                ('suspended', models.CharField(default='no', max_length=9999)),
                ('notes', models.TextField(default='noNotes', max_length=999999)),
            ],
        ),
    ]
