# Generated by Django 3.2.3 on 2022-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadeCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=100)),
                ('expires', models.DateField(blank=True)),
            ],
        ),
    ]
