# Generated by Django 3.2.3 on 2022-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadeCore', '0002_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires',
            field=models.DateTimeField(blank=True),
        ),
    ]
