# Generated by Django 4.1.2 on 2022-12-02 15:50

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=100)),
                ('head', models.CharField(default='no headline', max_length=500)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
