# Generated by Django 3.2.3 on 2022-12-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfoert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
