# Generated by Django 4.1.2 on 2022-12-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default=0, max_length=1)),
                ('minor', models.CharField(default=0, max_length=1)),
                ('patch', models.CharField(default=0, max_length=1)),
            ],
        ),
    ]
